-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.7.0
-- Generated: 2020-12-16 17:39 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.io_wrlds_sample_wrlds_event_1 (
    "schema_vendor"           VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"             VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"           VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version"          VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"                 CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"             TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"                VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"                VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"              VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "example_integer_field"   INT           ENCODE ZSTD NOT NULL,
    "example_string_field"    VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "example_timestamp_field" TIMESTAMP     ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.io_wrlds_sample_wrlds_event_1 IS 'iglu:io.wrlds/sample_wrlds_event/jsonschema/1-0-0';

ALTER TABLE atomic.io_wrlds_sample_wrlds_event_1 OWNER TO storageLoader;
